BookFPTStore/BookFPTStore/Areas/Admin/Controllers/AuthorController.cs
using BookFPTStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BookFPTStore.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize]
	public class AuthorController : Controller
	{
		public readonly FptbookstoreContext _dataContext;

		public AuthorController(FptbookstoreContext context)
		{
			_dataContext = context;
		}
		public IActionResult Index()
		{
			var authors = _dataContext.TbAuthors.ToList();
			return View(authors);
		}
		public IActionResult Create()
		{

			return View();
		}
		[HttpPost]
		public IActionResult Create(TbAuthor author)
		{
			if (ModelState.IsValid)
			{
				_dataContext.TbAuthors.Add(author);
				TempData["success"] = "Add Author Sucessfully!";
				_dataContext.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(author);
		}

		public async Task<IActionResult> Delete(int Id)
		{
			TbAuthor author = await _dataContext.TbAuthors.FindAsync(Id);
			_dataContext.TbAuthors.Remove(author);
			await _dataContext.SaveChangesAsync();
			TempData["success"] = "Delete Successful!";

			return RedirectToAction("Index");
		}
		public async Task<IActionResult> Edit(int Id)
		{
			TbAuthor author = await _dataContext.TbAuthors.FindAsync(Id);
			return View(author);
		}

		[HttpPost]

		public IActionResult Edit(TbAuthor author)
		{
			if (ModelState.IsValid)
			{
				_dataContext.TbAuthors.Update(author);
				TempData["success"] = "Update author Sucessfully!";
				_dataContext.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(author);
		}
	}
}

BookFPTStore/BookFPTStore/Areas/Admin/Controllers/CategoryController.cs
using BookFPTStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BookFPTStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]

    public class CategoryController : Controller
    {

        public readonly FptbookstoreContext _dataContext;

        public CategoryController(FptbookstoreContext context)
        {
            _dataContext = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _dataContext.TbCategories.OrderByDescending(p => p.Id).ToListAsync());
        }
        /*public IActionResult Index()
        {
            var categories = _dataContext.TbCategories.ToList();
            return View(categories);
        }*/
     

        public IActionResult Create(TbCategory category)
        {
            if (ModelState.IsValid)
            {
                _dataContext.TbCategories.Add(category);
                TempData["success"] = "Add Category Sucessfully!";
                _dataContext.SaveChanges();
                return RedirectToAction("Index"); 
            } 
            return View(category); 
        }

        public async Task<IActionResult> Edit(int Id)
        {
            TbCategory category = await _dataContext.TbCategories.FindAsync(Id);
            return View(category);
        }
        public IActionResult Update(TbCategory category)
        {
            if (ModelState.IsValid)
            {
                _dataContext.TbCategories.Update(category);
                TempData["success"] = "Update Category Sucessfully!";
                _dataContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public async Task<IActionResult> Delete(int Id)
        {
            TbCategory category = await _dataContext.TbCategories.FindAsync(Id);
            _dataContext.TbCategories.Remove(category);
            await _dataContext.SaveChangesAsync();
            TempData["success"] = "Delete Successful!";

            return RedirectToAction("Index");
        }

    }
}

BookFPTStore/BookFPTStore/Controllers/BookController.cs
using BookFPTStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookFPTStore.Controllers
{
    public class BookController : Controller
    {
		public readonly FptbookstoreContext _dataContext;
        private object category;

        public BookController(FptbookstoreContext context)
		{
			_dataContext = context;
		}
		

        public IActionResult Details(int Id)
        {
            var book = _dataContext.TbBooks
                           .Include(b => b.Category)
                           .Include(b => b.Author)
                           .FirstOrDefault(b => b.Id == Id);

            if (book == null)
            {
                return NotFound();
            }

            var data = new ViewClient
            {
                Book = book,
                Categories = _dataContext.TbCategories.ToList(),
                Authors = _dataContext.TbAuthors.ToList()
            };

            return View(data);

          
        }
    }
}

BookFPTStore/BookFPTStore/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Page</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminAssets/plugins/fontawesome-free/css/all.min.css">

    <!-- DataTables -->
    <link rel="stylesheet" href="~/AdminAssets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/AdminAssets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/AdminAssets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminAssets/dist/css/adminlte.min.css">
    <style>
        table .btn {
            margin: 5px 0px;
        }
    </style>
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    
    <div class="wrapper">
        <!-- Navbar -->
      
        @Html.Partial("_NavbarPartial")
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        @Html.Partial("_SidebarPartial")
        <!-- Content Wrapper. Contains page content -->
        
        <div class="content-wrapper">

            @if (TempData["success"] != null)
            {
                <div class="alert alert-success notification">
                    @TempData["success"]
                </div>
            }

            @if (TempData["error_ad"] != null)
            {
                <div class="alert alert-danger notification">
                    @TempData["error_ad"]
                </div>
            }

            <!-- Content Header (Page header) -->
            @RenderBody()
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.2.0
            </div>
            <strong>Fpt Book Store</strong> Admin.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminAssets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminAssets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');

        });
    </script>
    <!-- DataTables  & Plugins -->
    <script src="~/AdminAssets/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminAssets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/AdminAssets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/AdminAssets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/AdminAssets/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/AdminAssets/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/AdminAssets/plugins/jszip/jszip.min.js"></script>
    <script src="~/AdminAssets/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/AdminAssets/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/AdminAssets/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/AdminAssets/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/AdminAssets/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <!-- AdminLTE App -->
    <script src="~/AdminAssets/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminAssets/dist/js/demo.js"></script>

    @await RenderSectionAsync("Scripts", required:false)

</body>
</html>

BookFPTStore/BookFPTStore/Areas/Admin/Views/Shared/_NavbarPartial.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Category</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="../../dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="../../dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="../../dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

BookFPTStore/BookFPTStore/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/admin" class="brand-link">
        <img src="~/AdminAssets/dist/img/AdminLTELogo.png" alt="Admin FPTBOOK" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Admin FPTBOOK</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/AdminAssets/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">ADMIN</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Category Management
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Category" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>All Category</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Create" asp-controller="Category" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Category</p>
                            </a>
                        </li>
       
                    </ul>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Author Management
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Author" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>All Author</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Create" asp-controller="Author" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Author</p>
                            </a>
                        </li>

                    </ul>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-book"></i>
                        <p>
                            Book Management
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Book" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>All Book</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Create" asp-controller="Book" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Book</p>
                            </a>
                        </li>

                    </ul>
                </li>

                <li class="nav-item">
                    <a class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            User Management
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="User" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>All User</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Account/Create" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add User</p>
                            </a>
                        </li>

                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>